In [ ]:
# Make two points
# Find point that minimizes distance from the two points

In [3]:
a = 2, 2
b = 4, 4

In [4]:
from scipy.spatial.distance import euclidean

In [5]:
euclidean(a, b)

2.8284271247461903

In [6]:
points = [a, b]

def f(x):
    distances = [euclidean(x, _) for _ in points]
    return sum(distances) + max(distances)

f((0, 0))

14.142135623730951

In [22]:
f((1, 1))

5.6568542494923797

In [23]:
f((2, 2))

2.8284271247461903

In [7]:
from scipy.optimize import minimize

In [25]:
minimize(f, (0, 0))

   status: 2
  success: False
     njev: 31
     nfev: 134
 hess_inv: array([[ 1.67389679,  0.67389679],
       [ 0.67389679,  1.67389679]])
      fun: 4.242640694867561
        x: array([ 2.99999999,  2.99999999])
  message: 'Desired error not necessarily achieved due to precision loss.'
      jac: array([-0.33284914, -0.33284914])

In [12]:
minimize(f, (100, 0))

   status: 0
  success: True
     njev: 13
     nfev: 52
 hess_inv: array([[ 1.12733562,  0.32863138],
       [ 0.32863138,  0.94047033]])
      fun: 2.828427124747292
        x: array([ 3.05018538,  3.05018714])
  message: 'Optimization terminated successfully.'
      jac: array([ -1.22189522e-06,   1.25169754e-06])

In [26]:
minimize(f, (100, 100))

   status: 2
  success: False
     njev: 68
     nfev: 284
 hess_inv: array([[ 0.5, -0.5],
       [-0.5,  0.5]])
      fun: 4.242640691203315
        x: array([ 3.,  3.])
  message: 'Desired error not necessarily achieved due to precision loss.'
      jac: array([ 0.1589576,  0.1589576])

In [28]:
minimize(f, (2, 2))

   status: 2
  success: False
     njev: 41
     nfev: 168
 hess_inv: array([[1, 0],
       [0, 1]])
      fun: 5.6568542494923806
        x: array([2, 2])
  message: 'Desired error not necessarily achieved due to precision loss.'
      jac: array([-0.4142136, -0.4142136])

In [29]:
f((2, 2))

5.6568542494923806

In [33]:
f((3, 3))

4.2426406871192857

In [32]:
result = minimize(f, (3, 3))
result

   status: 2
  success: False
     njev: 12
     nfev: 60
 hess_inv: array([[1, 0],
       [0, 1]])
      fun: 4.2426406871192857
        x: array([3, 3])
  message: 'Desired error not necessarily achieved due to precision loss.'
      jac: array([ 0.70710677,  0.70710677])

In [18]:
f((3, 3))

2.8284271247461903

In [17]:
result.items()

[('status', 0),
 ('success', True),
 ('njev', 1),
 ('nfev', 4),
 ('hess_inv', array([[1, 0],
         [0, 1]])),
 ('fun', 2.8284271247461903),
 ('x', array([3, 3])),
 ('message', 'Optimization terminated successfully.'),
 ('jac', array([ 0.,  0.]))]

In [7]:
# We should try different starting points
points

[(2, 2), (4, 4)]

In [10]:
import numpy as np
x = np.array(points)
x

array([[2, 2],
       [4, 4]])

In [13]:
x.min(axis=0)

array([2, 2])

In [14]:
x.max(axis=0)

array([4, 4])

In [15]:
import random

In [17]:
random.random?

In [19]:
random.uniform(2, 4)

3.1434240235812263

In [20]:
x = random.uniform(2, 4), random.uniform(2, 4)
x

(2.50342796757858, 3.6101867705219304)

In [21]:
from scipy.optimize import minimize

In [22]:
points

[(2, 2), (4, 4)]

In [23]:
minimize(f, x)

   status: 2
  success: False
     njev: 35
     nfev: 152
 hess_inv: array([[ 0.21047083, -0.14862479],
       [-0.14862479,  0.19692104]])
      fun: 4.250127738447917
        x: array([ 3.0594352,  2.9405648])
  message: 'Desired error not necessarily achieved due to precision loss.'
      jac: array([ 0.64174747,  0.39002943])

In [ ]:
import numpy as np

interest_points = [
    (2, 2),
    (4, 4),
]

def place_hotspots(interest_points, hotspot_count, hotspot_radius, iteration_count):
    interest_points = np.array(interest_points)
    interest_tree
    
    def compute_loss(hotspot_points):
        # for each hotspot, get interest points within radius
        # compute summed distance of hotspot to interest points
        # also add max distance
        
        # subtract the distance from other hotspots (we want to maximize this)
        
        # sum over all hotspots
        pass
    
    # for each iteration
    # initialize randomly
    # minimize
    
    # choose iteration that has best loss